language: c
compiler: gcc
before_install:
## Fix apt preferences for libconfig
#- "echo 'Package: libconfig*' | sudo tee -a /etc/apt/preferences"
#- "echo 'Pin: release n=quantal*' | sudo tee -a /etc/apt/preferences"
#- "echo 'Pin-Priority: 990' | sudo tee -a /etc/apt/preferences"
#- sudo DEBIAN_FRONTEND=noninteractive apt-get -qq -y --fix-missing -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew dist-upgrade
#- sudo add-apt-repository ppa:mosquitto-dev/mosquitto-ppa -y
- sudo DEBCONF_NONINTERACTIVE_SEEN=true DEBIAN_FRONTEND=noninteractive apt-get update -qq
- apt-cache search mosquitto
- sudo apt-get install -qq libmosquitto-dev libconfig8-dev liblmdb-dev
script:
- cp config.mk.in config.mk
- make
- ./ocat -v
notifications:
  slack:
    secure: AWI43ztcN3D/TW3U2CQwuVKLrHqQk7xShuMm8d2JUfTuHtamRvhQ3jAYs3NdfA2brlJKiOHl6HLbbGRaT6ITdcel1UuAmKzNbuKw+jM9ug2ziGddmAeyoQ3DrjECCnydZ3YAEKtAvRFAl3Q+AmXDUkiFOV988lLQ3PkG2ODcwI/4KS3IM/H0SrDy6/ejAG8unICZfXs49XJRGI0kEj3Xzy8OUE1cdB9BGzTaQi/kOsHVgu/CUMwY/ofeRBRaYPqnj3ewgGJmRyLh2A1z6OSPRMkoSgS1u8a5OsiWgAL1j0rZZDws9MwkI3Lkkvw3rO2Gn3uRzMvzXx3/h+B9qBEH3L7NulDQNu8MY5iH6Bx/3m9eom79JJgN31+RDjjCrtNVlBj7bXjtrJJqNtL4EOXFMvjq3MgnMwREtBtIqj+xufRdJGQGfyvF4YA2MT96CTGtr1udTnD3E6S0n2XjTI9cBVty9FYG5juDGh5BwNk9HDttLusjQQ+8CbNnQjh3ILAiNRNhQNRL1M6MK8GJbtMfiWRYG5HZgfY4ZmKWAuYS67fJw4TSkNPtUMTiwRSdDckNaqfdLU9XNzBnHnswcr8ZRAdsWkWr4XmysLL3/XnRN3awLDGoibs65Yd7fg1TqV/9HWjpDmcwUOs5o06MIfFPakhYj1D+ebm+DwS9KoxawvE=
